---
title: "Project"
author: "Priya Bajaj"
date: "2/21/2020"
output: html_document
---

```{r}
library("tidyverse")
```

```{r}
getwd()
```


```{r}
Data <- readr::read_csv("Copy.csv")
```

```{r}
glimpse(Data)
```

```{r}

```


```{r}
row.names(Data)
```

```{r}
summary(Data)
```


```{r}
anyNA(Data)
```

```{r}
Data2 <- Data %>% 
  rename(Activity_Reduction="Cut down on the amount of time you spent on work or other activities?", Less_Accomplished="Accomplished less than you would like?", Less_Careful_Work= "Did work or other activities less carefully than ususal?", Physical_Emotional_Health_VS_Social= "Has your physical health or emotional problems interfered with your normal social activities?", Health_VS_SocialAct.="Has your health limited your social activities?", Nervousness= "Have you been a very nervous person?", Un_Cheerable="Have you felt so down in the dumps that nothing could cheer you up?", Calm="Have you felt calm and peaceful?",Downhearted="Have you felt downhearted and blue?", Happy="Have you been a happy person?")
         
```

```{r}
Data2 %>% 
  separate(Activity_Reduction, into= c("patient", "sex"), sep = "_")
```


```{r}
help("")
```